package Chess;

/**
 * Created by Ilian on 2016-04-05.
 */
public enum PieceType {
    EMPTY,BLACK_PAWN,BLACK_ROOK,BLACK_KNIGHT,BLACK_BISHOP,BLACK_QUEEN,BLACK_KING
    ,WHITE_PAWN,WHITE_ROOK,WHITE_KNIGHT,WHITE_BISHOP,WHITE_QUEEN,WHITE_KING;
}
